//------------------------------------------------------------------------------
// AssemblyInfo.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using Microsoft.Dss.Core.Attributes;

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Reflection;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: ComVisible(false)]

[assembly: AssemblyTitle("Simulated Differential Drive Service")]
[assembly: AssemblyProduct("Simulated Differential Drive Service")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyCopyright("Written by Trevor Taylor (Jul 2007)")]
[assembly: AssemblyDescription("Modified Differential Drive with extra features. Built for MSRS V1.5. This version is freely available.")]
[assembly: AssemblyCompany("Queensland University of Technology")]

// TT
[assembly: CLSCompliant(true)]


